### PR TITLE
Improve messages

### PR DESCRIPTION
**Pull request by awoo-civ**
I've tried to fix up the english and do some rewording. I'm not sure about some parts though:
- I've assumed [here](https://github.com/Aleksey-Terzi/CastleGates/compare/master...iykHvfIvfR:pr3?expand=1#diff-f06162008ae5e2c6e83f0413c173e2caR273) and [here](https://github.com/Aleksey-Terzi/CastleGates/compare/master...iykHvfIvfR:pr3?expand=1#diff-f06162008ae5e2c6e83f0413c173e2caR389) that it's the gearblock that's undrawn, is that correct?
- I'm not sure if [this](https://github.com/Aleksey-Terzi/CastleGates/compare/master...iykHvfIvfR:pr3?expand=1#diff-f06162008ae5e2c6e83f0413c173e2caR321) part is correct

### CODE REVIEW

**Comment by Aleksey-Terzi** [comment]
> I've assumed here and here that it's the gearblock that's undrawn, is that correct?  

Even not sure.
Technically it is link is in drawn/undrawn state, but gearblocks are just points.
But do you think it will sound better if we will use here gearblock term instead?

> I'm not sure if this part is correct

This is correct.
What this mean:

1) We have two linked gearblocks for example over bastioned trench

2) Owner drawn bridge

3) Raider broken one of gearblocks, but since other gearblock is still exist - then link with bridge blocks still exist too

4) Then owner is trying to restore bridge. If he/she wants to make this correctly - then gearblock should be placed in exactly the same place where it was. But if he/she is putting it in wrong place and then trying to link - then will be shown this message.

**Comment by awoo-civ** [comment]
> Even not sure.
> Technically it is link is in drawn/undrawn state, but gearblocks are just points.
> But do you think it will sound better if we will use here gearblock term instead?

Yea, the users would probably be much less confused by that, though I think the 'bridge/gate' term would be even better, so I [went with it](https://github.com/Aleksey-Terzi/CastleGates/pull/5/commits/7a7fe8571567fcedd80884ef1d355aeb26ff9e0c#diff-f06162008ae5e2c6e83f0413c173e2caL273).

BTW, what's up with that anyway, wouldn't it be easier to just say 'gates' everywhere? There isn't really a difference between a bridge and a gate from a technical standpoint, is there?

> This is correct.
> What this mean:
> [...]

Ah, that explains it, thanks.

I've decided to go with a [message that's a bit longer than the original](https://github.com/Aleksey-Terzi/CastleGates/pull/5/commits/7a7fe8571567fcedd80884ef1d355aeb26ff9e0c#diff-f06162008ae5e2c6e83f0413c173e2caL321), for the sake of making sure the user understands what's going on and how to fix it. I don't think the length should be much of an issue as the message doesn't get displayed very often. 

Now, I've noticed that the way coordinates are formatted is rather verbose:
`gearblock at x = -2011, y = 20, z = 2000`
Is there any reason not to use the shorter `gearblock at [-2011 20 2000]` instead?

**Comment by Aleksey-Terzi** [comment]
> Yea, the users would probably be much less confused by that, though I think the 'bridge/gate' term would be even better, so I went with it.

Thanks, this definitely better.

> BTW, what's up with that anyway, wouldn't it be easier to just say 'gates' everywhere? There isn't really a difference between a bridge and a gate from a technical standpoint, is there?

I think better to use "bridge/gate" just to avoid confusion.

> I've decided to go with a message that's a bit longer than the original, for the sake of making sure the user understands what's going on and how to fix it. I don't think the length should be much of an issue as the message doesn't get displayed very often.

Yes, agree.

> Is there any reason not to use the shorter gearblock at [-2011 20 2000] instead?

The only one reason - this was temporary format (used in few places) and later I forgot to change it :)
But what you proposed is much better and easy remembering in memory (contradict to my format).
I would appreciate if you will change format as well.

**Comment by awoo-civ** [comment]
Alright, done :)

One more thing - some messages end with periods, others don't. Which do you prefer?

**Comment by Aleksey-Terzi** [comment]
> Alright, done :)

Thanks!

> One more thing - some messages end with periods, others don't. Which do you prefer?

Mmm, maybe period is better.
But actually is up to you, in both cases but when the same format for all messages - will look much better.

**Comment by awoo-civ** [comment]
Ok, all done. I can't think of any more changes, so go ahead and merge if you like how everything looks like now.

**Comment by Aleksey-Terzi** [comment]
Looks good, thank you!

**Pull request merged**
